version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    container_name: ${App_Name}-app
    working_dir: /var/www/root
    volumes:
    - ./root:/var/www/root
    ports:
      # - "8000:8000"
      - "5173:5173"
    restart: always

  web:
    image: nginx:latest
    container_name: ${App_Name}-nginx
    ports:
      - "80:80"
    volumes:
      - ./root:/var/www/root
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: always

  db:
    image: mysql:8.0
    container_name: ${App_Name}-mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      # MYSQL_USER: ${DB_USERNAME}
      # MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: always

volumes:
  dbdata:
